pipeline:

  deploy:
    image: docker:1.13-dind
    commands:
      - docker deploy --compose-file docker-compose.yml drone

services:
  dind:
    image: docker:1.13-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
